<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Restaurant;

class RestaurantSeeder extends Seeder
{
    public function run()
    {
       $data = [
            [
                'name' => 'Tacibay',
                'address' => 'Belakang Polinema',
                'distance'  => '0.8 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 3,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 2,
                'kriteria_jam_operasional_id' => 2,
                'variasi_menu_id' => 5,
                'active' => 1,
            ],
            [
                'name' => 'Dapur Sedep',
                'address' => 'Belakang Polinema',
                'distance'  => '0.3 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 6,
                'average' => 6000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_jam_operasional_id' => 1,
                'variasi_menu_id' => 4,
                'active' => 1,
            ],
            [
                'name' => 'Lalapan Tosa',
                'address' => 'Belakang Polinema',
                'distance'  => '1 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 8,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 3,
                'kriteria_jam_operasional_id' => 2,
                'variasi_menu_id' => 4,
                'active' => 1,
            ],
            [
                'name' => 'Warung Mama',
                'address' => 'Belakang Polinema',
                'distance'  => '2 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 20,
                'average' => 7000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 2,
                'kriteria_jam_operasional_id' => 2,
                'variasi_menu_id' => 2,
                'active' => 1,
            ],
            [
                'name' => 'Ayam Penyet Banyuangi',
                'address' => 'Belakang Polinema',
                'distance'  => '3 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 10,
                'average' => 10000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 3,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 3,
                'active' => 1,
            ],
            [
                'name' => 'Rawon Cak Wott',
                'address' => 'Belakang Polinema',
                'distance'  => '3.5 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 14,
                'average' => 10000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 3,
                'kriteria_fasilitas_id' => 2,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 3,
                'active' => 1,
            ],
            [
                'name' => 'Warung EWK Lapapan Aneka Sambel',
                'address' => 'Belakang Polinema',
                'distance'  => '0.5 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 8,
                'average' => 2,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 4,
                'active' => 1,
            ],
            [
                'name' => 'Kedai Makcik',
                'address' => 'Belakang Polinema',
                'distance'  => '1 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 20,
                'average' => 2000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 2,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 2,
                'active' => 1,
            ],
            [
                'name' => 'Lalapan Ayam Qodir',
                'address' => 'Belakang Polinema',
                'distance'  => '1.5 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 10,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 2,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 3,
                'active' => 1,
            ],
            [
                'name' => 'Warung Ijo',
                'address' => 'Belakang Polinema',
                'distance'  => '4 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 5,
                'average' => 4000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 3,
                'kriteria_fasilitas_id' => 2,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 4,
                'active' => 1,
            ],
            [
                'name' => 'Warung Geprek Ragil',
                'address' => 'Belakang Polinema',
                'distance'  => '1 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 4,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 3,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 5,
                'active' => 1,
            ],
            [
                'name' => 'Ayam Goreng Nelongso',
                'address' => 'Belakang Polinema',
                'distance'  => '0.4 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 10,
                'average' => 25000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 2,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_jam_operasional_id' => 5,
                'variasi_menu_id' => 4,
                'active' => 1,
            ],
            [
                'name' => 'Soto Ayam Cak Man',
                'address' => 'Belakang Polinema',
                'distance'  => '3 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 2,
                'average' => 30000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 3,
                'kriteria_jarak_id' => 3,
                'kriteria_fasilitas_id' => 1,
                'kriteria_jam_operasional_id' => 1,
                'variasi_menu_id' => 5,
                'active' => 1,
            ],
            [
                'name' => 'Warung Soto Madura Cak Mad',
                'address' => 'Belakang Polinema',
                'distance'  => '0.2 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 5,
                'average' => 10000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_jam_operasional_id' => 3,
                'variasi_menu_id' => 4,
                'active' => 1,
            ],
            [
                'name' => 'Warung Makan & Kopi "Tegar"',
                'address' => 'Belakang Polinema',
                'distance'  => '0.4 KM',
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 8,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 2,
                'kriteria_jam_operasional_id' => 4,
                'variasi_menu_id' => 4,
                'active' => 1,
            ],
        ];

        Restaurant::insert($data);
    }
}
