<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Restaurant;

class RestaurantSeeder extends Seeder
{
    public function run()
    {
       $data = [
            [
                'name' => 'Tacibay',
                'address' => 'Belakang Polinema',
                'distance'  => 800,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 3,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 2,
                'kriteria_rasa_id' => 2,
                'variasi_menu_id' => 5,
            ],
            [
                'name' => 'Dapur Sedep',
                'address' => 'Belakang Polinema',
                'distance'  => 300,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 6,
                'average' => 6000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_rasa_id' => 1,
                'variasi_menu_id' => 4,
            ],
            [
                'name' => 'Lalapan Tosa',
                'address' => 'Belakang Polinema',
                'distance'  => 1000,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 8,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 3,
                'kriteria_rasa_id' => 2,
                'variasi_menu_id' => 4,
            ],
            [
                'name' => 'Warung Mama',
                'address' => 'Belakang Polinema',
                'distance'  => 2000,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 20,
                'average' => 7000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 2,
                'kriteria_rasa_id' => 2,
                'variasi_menu_id' => 2,
            ],
            [
                'name' => 'Ayam Penyet Banyuangi',
                'address' => 'Belakang Polinema',
                'distance'  => 3000,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 10,
                'average' => 10000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 3,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 3,
            ],
            [
                'name' => 'Rawon Cak Wott',
                'address' => 'Belakang Polinema',
                'distance'  => 3500,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 14,
                'average' => 10000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 3,
                'kriteria_fasilitas_id' => 2,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 3,
            ],
            [
                'name' => 'Warung EWK Lapapan Aneka Sambel',
                'address' => 'Belakang Polinema',
                'distance'  => 500,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 8,
                'average' => 2,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 4,
            ],
            [
                'name' => 'Kedai Makcik',
                'address' => 'Belakang Polinema',
                'distance'  => 1000,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 20,
                'average' => 2000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 2,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 2,
            ],
            [
                'name' => 'Lalapan Ayam Qodir',
                'address' => 'Belakang Polinema',
                'distance'  => 1500,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 10,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 2,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 3,
            ],
            [
                'name' => 'Warung Ijo',
                'address' => 'Belakang Polinema',
                'distance'  => 4000,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 5,
                'average' => 4000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 3,
                'kriteria_fasilitas_id' => 2,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 4,
            ],
            [
                'name' => 'Warung Geprek Ragil',
                'address' => 'Belakang Polinema',
                'distance'  => 1000,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 4,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 2,
                'kriteria_fasilitas_id' => 3,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 5,
            ],
            [
                'name' => 'Ayam Goreng Nelongso',
                'address' => 'Belakang Polinema',
                'distance'  => 400,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 10,
                'average' => 25000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 2,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_rasa_id' => 5,
                'variasi_menu_id' => 4,
            ],
            [
                'name' => 'Soto Ayam Cak Man',
                'address' => 'Belakang Polinema',
                'distance'  => 3000,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 2,
                'average' => 30000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 3,
                'kriteria_jarak_id' => 3,
                'kriteria_fasilitas_id' => 1,
                'kriteria_rasa_id' => 1,
                'variasi_menu_id' => 5,
            ],
            [
                'name' => 'Warung Soto Madura Cak Mad',
                'address' => 'Belakang Polinema',
                'distance'  => 200,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 5,
                'average' => 10000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 3,
                'kriteria_rasa_id' => 3,
                'variasi_menu_id' => 4,
            ],
            [
                'name' => 'Warung Makan & Kopi "Tegar"',
                'address' => 'Belakang Polinema',
                'distance'  => 400,
                'images'   => null,
                'facility'  => 'Toilet, Musholla',
                'qty_variasi_makanan' => 8,
                'average' => 5000.00,
                'status' => 1,
                'added_by'  => 'admin',
                'kriteria_harga_id' => 1,
                'kriteria_jarak_id' => 1,
                'kriteria_fasilitas_id' => 2,
                'kriteria_rasa_id' => 4,
                'variasi_menu_id' => 4,
            ],
        ];

        Restaurant::insert($data);
    }
}
